### Post Users data
POST  http://localhost:4000/users/sorted
Content-Type: application/json

{
  "users": [
    {
      "id": 1,
      "name": "John Doe",
      "email": "john@example.com",
      "tasks": [
        { "id": 1, "description": "Task 1", "status": "complete" },
        { "id": 2, "description": "Task 2", "status": "incomplete" }
      ]
    },
    {
      "id": 2,
      "name": "Jane Smith",
      "email": "jane@example.com",
      "tasks": [
        { "id": 1, "description": "Task 1", "status": "complete" },
        { "id": 2, "description": "Task 2", "status": "complete" }
      ]
    }
  ]
}